"""Add is_assigned to driverassignments

Revision ID: 24167965f446
Revises: f18f11ffe40b
Create Date: 2026-08-31 15:47:59.150762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24167965f446'
down_revision = 'f18f11ffe40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_assigned', sa.Boolean(), nullable=False,server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_assignments', schema=None) as batch_op:
        batch_op.drop_column('is_assigned')

    # ### end Alembic commands ###
